// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srcctl.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Cache struct {
	Request              string               `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Responce             string               `protobuf:"bytes,2,opt,name=responce,proto3" json:"responce,omitempty"`
	ResStatus            int32                `protobuf:"varint,3,opt,name=resStatus,proto3" json:"resStatus,omitempty"`
	RefreshDate          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=refreshDate,proto3" json:"refreshDate,omitempty"`
	RequestDate          *timestamp.Timestamp `protobuf:"bytes,5,opt,name=requestDate,proto3" json:"requestDate,omitempty"`
	AskCount             int32                `protobuf:"varint,6,opt,name=askCount,proto3" json:"askCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Cache) Reset()         { *m = Cache{} }
func (m *Cache) String() string { return proto.CompactTextString(m) }
func (*Cache) ProtoMessage()    {}
func (*Cache) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e322a80f26f6710, []int{0}
}

func (m *Cache) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cache.Unmarshal(m, b)
}
func (m *Cache) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cache.Marshal(b, m, deterministic)
}
func (m *Cache) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cache.Merge(m, src)
}
func (m *Cache) XXX_Size() int {
	return xxx_messageInfo_Cache.Size(m)
}
func (m *Cache) XXX_DiscardUnknown() {
	xxx_messageInfo_Cache.DiscardUnknown(m)
}

var xxx_messageInfo_Cache proto.InternalMessageInfo

func (m *Cache) GetRequest() string {
	if m != nil {
		return m.Request
	}
	return ""
}

func (m *Cache) GetResponce() string {
	if m != nil {
		return m.Responce
	}
	return ""
}

func (m *Cache) GetResStatus() int32 {
	if m != nil {
		return m.ResStatus
	}
	return 0
}

func (m *Cache) GetRefreshDate() *timestamp.Timestamp {
	if m != nil {
		return m.RefreshDate
	}
	return nil
}

func (m *Cache) GetRequestDate() *timestamp.Timestamp {
	if m != nil {
		return m.RequestDate
	}
	return nil
}

func (m *Cache) GetAskCount() int32 {
	if m != nil {
		return m.AskCount
	}
	return 0
}

type AllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllRequest) Reset()         { *m = AllRequest{} }
func (m *AllRequest) String() string { return proto.CompactTextString(m) }
func (*AllRequest) ProtoMessage()    {}
func (*AllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e322a80f26f6710, []int{1}
}

func (m *AllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllRequest.Unmarshal(m, b)
}
func (m *AllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllRequest.Marshal(b, m, deterministic)
}
func (m *AllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllRequest.Merge(m, src)
}
func (m *AllRequest) XXX_Size() int {
	return xxx_messageInfo_AllRequest.Size(m)
}
func (m *AllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllRequest proto.InternalMessageInfo

type AllReply struct {
	Cache                []*Cache `protobuf:"bytes,1,rep,name=cache,proto3" json:"cache,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllReply) Reset()         { *m = AllReply{} }
func (m *AllReply) String() string { return proto.CompactTextString(m) }
func (*AllReply) ProtoMessage()    {}
func (*AllReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e322a80f26f6710, []int{2}
}

func (m *AllReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllReply.Unmarshal(m, b)
}
func (m *AllReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllReply.Marshal(b, m, deterministic)
}
func (m *AllReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllReply.Merge(m, src)
}
func (m *AllReply) XXX_Size() int {
	return xxx_messageInfo_AllReply.Size(m)
}
func (m *AllReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AllReply.DiscardUnknown(m)
}

var xxx_messageInfo_AllReply proto.InternalMessageInfo

func (m *AllReply) GetCache() []*Cache {
	if m != nil {
		return m.Cache
	}
	return nil
}

type TopNRequest struct {
	N                    int32    `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopNRequest) Reset()         { *m = TopNRequest{} }
func (m *TopNRequest) String() string { return proto.CompactTextString(m) }
func (*TopNRequest) ProtoMessage()    {}
func (*TopNRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e322a80f26f6710, []int{3}
}

func (m *TopNRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopNRequest.Unmarshal(m, b)
}
func (m *TopNRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopNRequest.Marshal(b, m, deterministic)
}
func (m *TopNRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopNRequest.Merge(m, src)
}
func (m *TopNRequest) XXX_Size() int {
	return xxx_messageInfo_TopNRequest.Size(m)
}
func (m *TopNRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TopNRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TopNRequest proto.InternalMessageInfo

func (m *TopNRequest) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

type TopNReply struct {
	Cache                []*Cache `protobuf:"bytes,1,rep,name=cache,proto3" json:"cache,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopNReply) Reset()         { *m = TopNReply{} }
func (m *TopNReply) String() string { return proto.CompactTextString(m) }
func (*TopNReply) ProtoMessage()    {}
func (*TopNReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e322a80f26f6710, []int{4}
}

func (m *TopNReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopNReply.Unmarshal(m, b)
}
func (m *TopNReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopNReply.Marshal(b, m, deterministic)
}
func (m *TopNReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopNReply.Merge(m, src)
}
func (m *TopNReply) XXX_Size() int {
	return xxx_messageInfo_TopNReply.Size(m)
}
func (m *TopNReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TopNReply.DiscardUnknown(m)
}

var xxx_messageInfo_TopNReply proto.InternalMessageInfo

func (m *TopNReply) GetCache() []*Cache {
	if m != nil {
		return m.Cache
	}
	return nil
}

type LastNRequest struct {
	N                    int32    `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastNRequest) Reset()         { *m = LastNRequest{} }
func (m *LastNRequest) String() string { return proto.CompactTextString(m) }
func (*LastNRequest) ProtoMessage()    {}
func (*LastNRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e322a80f26f6710, []int{5}
}

func (m *LastNRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastNRequest.Unmarshal(m, b)
}
func (m *LastNRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastNRequest.Marshal(b, m, deterministic)
}
func (m *LastNRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastNRequest.Merge(m, src)
}
func (m *LastNRequest) XXX_Size() int {
	return xxx_messageInfo_LastNRequest.Size(m)
}
func (m *LastNRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LastNRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LastNRequest proto.InternalMessageInfo

func (m *LastNRequest) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

type LastNReply struct {
	Cache                []*Cache `protobuf:"bytes,1,rep,name=cache,proto3" json:"cache,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastNReply) Reset()         { *m = LastNReply{} }
func (m *LastNReply) String() string { return proto.CompactTextString(m) }
func (*LastNReply) ProtoMessage()    {}
func (*LastNReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e322a80f26f6710, []int{6}
}

func (m *LastNReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastNReply.Unmarshal(m, b)
}
func (m *LastNReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastNReply.Marshal(b, m, deterministic)
}
func (m *LastNReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastNReply.Merge(m, src)
}
func (m *LastNReply) XXX_Size() int {
	return xxx_messageInfo_LastNReply.Size(m)
}
func (m *LastNReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LastNReply.DiscardUnknown(m)
}

var xxx_messageInfo_LastNReply proto.InternalMessageInfo

func (m *LastNReply) GetCache() []*Cache {
	if m != nil {
		return m.Cache
	}
	return nil
}

type SettingsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SettingsRequest) Reset()         { *m = SettingsRequest{} }
func (m *SettingsRequest) String() string { return proto.CompactTextString(m) }
func (*SettingsRequest) ProtoMessage()    {}
func (*SettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e322a80f26f6710, []int{7}
}

func (m *SettingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettingsRequest.Unmarshal(m, b)
}
func (m *SettingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettingsRequest.Marshal(b, m, deterministic)
}
func (m *SettingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettingsRequest.Merge(m, src)
}
func (m *SettingsRequest) XXX_Size() int {
	return xxx_messageInfo_SettingsRequest.Size(m)
}
func (m *SettingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SettingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SettingsRequest proto.InternalMessageInfo

type SettingsReply struct {
	Settings             []string `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SettingsReply) Reset()         { *m = SettingsReply{} }
func (m *SettingsReply) String() string { return proto.CompactTextString(m) }
func (*SettingsReply) ProtoMessage()    {}
func (*SettingsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e322a80f26f6710, []int{8}
}

func (m *SettingsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettingsReply.Unmarshal(m, b)
}
func (m *SettingsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettingsReply.Marshal(b, m, deterministic)
}
func (m *SettingsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettingsReply.Merge(m, src)
}
func (m *SettingsReply) XXX_Size() int {
	return xxx_messageInfo_SettingsReply.Size(m)
}
func (m *SettingsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SettingsReply.DiscardUnknown(m)
}

var xxx_messageInfo_SettingsReply proto.InternalMessageInfo

func (m *SettingsReply) GetSettings() []string {
	if m != nil {
		return m.Settings
	}
	return nil
}

type CleanRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CleanRequest) Reset()         { *m = CleanRequest{} }
func (m *CleanRequest) String() string { return proto.CompactTextString(m) }
func (*CleanRequest) ProtoMessage()    {}
func (*CleanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e322a80f26f6710, []int{9}
}

func (m *CleanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CleanRequest.Unmarshal(m, b)
}
func (m *CleanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CleanRequest.Marshal(b, m, deterministic)
}
func (m *CleanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CleanRequest.Merge(m, src)
}
func (m *CleanRequest) XXX_Size() int {
	return xxx_messageInfo_CleanRequest.Size(m)
}
func (m *CleanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CleanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CleanRequest proto.InternalMessageInfo

type CleanReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CleanReply) Reset()         { *m = CleanReply{} }
func (m *CleanReply) String() string { return proto.CompactTextString(m) }
func (*CleanReply) ProtoMessage()    {}
func (*CleanReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e322a80f26f6710, []int{10}
}

func (m *CleanReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CleanReply.Unmarshal(m, b)
}
func (m *CleanReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CleanReply.Marshal(b, m, deterministic)
}
func (m *CleanReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CleanReply.Merge(m, src)
}
func (m *CleanReply) XXX_Size() int {
	return xxx_messageInfo_CleanReply.Size(m)
}
func (m *CleanReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CleanReply.DiscardUnknown(m)
}

var xxx_messageInfo_CleanReply proto.InternalMessageInfo

type RefreshRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshRequest) Reset()         { *m = RefreshRequest{} }
func (m *RefreshRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshRequest) ProtoMessage()    {}
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e322a80f26f6710, []int{11}
}

func (m *RefreshRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshRequest.Unmarshal(m, b)
}
func (m *RefreshRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshRequest.Marshal(b, m, deterministic)
}
func (m *RefreshRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshRequest.Merge(m, src)
}
func (m *RefreshRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshRequest.Size(m)
}
func (m *RefreshRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshRequest proto.InternalMessageInfo

type RefreshReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshReply) Reset()         { *m = RefreshReply{} }
func (m *RefreshReply) String() string { return proto.CompactTextString(m) }
func (*RefreshReply) ProtoMessage()    {}
func (*RefreshReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e322a80f26f6710, []int{12}
}

func (m *RefreshReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshReply.Unmarshal(m, b)
}
func (m *RefreshReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshReply.Marshal(b, m, deterministic)
}
func (m *RefreshReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshReply.Merge(m, src)
}
func (m *RefreshReply) XXX_Size() int {
	return xxx_messageInfo_RefreshReply.Size(m)
}
func (m *RefreshReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshReply.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Cache)(nil), "pb.Cache")
	proto.RegisterType((*AllRequest)(nil), "pb.AllRequest")
	proto.RegisterType((*AllReply)(nil), "pb.AllReply")
	proto.RegisterType((*TopNRequest)(nil), "pb.TopNRequest")
	proto.RegisterType((*TopNReply)(nil), "pb.TopNReply")
	proto.RegisterType((*LastNRequest)(nil), "pb.LastNRequest")
	proto.RegisterType((*LastNReply)(nil), "pb.LastNReply")
	proto.RegisterType((*SettingsRequest)(nil), "pb.SettingsRequest")
	proto.RegisterType((*SettingsReply)(nil), "pb.SettingsReply")
	proto.RegisterType((*CleanRequest)(nil), "pb.CleanRequest")
	proto.RegisterType((*CleanReply)(nil), "pb.CleanReply")
	proto.RegisterType((*RefreshRequest)(nil), "pb.RefreshRequest")
	proto.RegisterType((*RefreshReply)(nil), "pb.RefreshReply")
}

func init() { proto.RegisterFile("srcctl.proto", fileDescriptor_1e322a80f26f6710) }

var fileDescriptor_1e322a80f26f6710 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcb, 0x6e, 0xdb, 0x30,
	0x10, 0x0c, 0xed, 0xc8, 0xb1, 0xd6, 0x8c, 0xe2, 0x6c, 0x2f, 0x02, 0x1b, 0x20, 0x86, 0x80, 0x02,
	0x02, 0xd2, 0x2a, 0xa8, 0xdb, 0x63, 0x2f, 0x81, 0x7b, 0x2c, 0x7a, 0x60, 0xf2, 0x03, 0xb2, 0xc0,
	0x38, 0x41, 0x69, 0x89, 0x15, 0xa9, 0x83, 0xff, 0xa5, 0x7f, 0xd9, 0x1f, 0x28, 0x48, 0xea, 0xe5,
	0x02, 0x01, 0x7c, 0x9c, 0x99, 0xdd, 0xe1, 0xec, 0x48, 0x40, 0x75, 0x5d, 0x14, 0x46, 0x66, 0xaa,
	0xae, 0x4c, 0x85, 0x13, 0xb5, 0x65, 0xb7, 0xbb, 0xaa, 0xda, 0x49, 0x71, 0xef, 0x98, 0x6d, 0xf3,
	0x7c, 0x6f, 0x5e, 0xf7, 0x42, 0x9b, 0x7c, 0xaf, 0xfc, 0x50, 0xf2, 0x97, 0x40, 0xb0, 0xc9, 0x8b,
	0x17, 0x81, 0x31, 0x5c, 0xd4, 0xe2, 0x77, 0x23, 0xb4, 0x89, 0xc9, 0x8a, 0xa4, 0x21, 0xef, 0x20,
	0x32, 0x98, 0xd7, 0x42, 0xab, 0xaa, 0x2c, 0x44, 0x3c, 0x71, 0x52, 0x8f, 0xf1, 0x06, 0xc2, 0x5a,
	0xe8, 0x47, 0x93, 0x9b, 0x46, 0xc7, 0xd3, 0x15, 0x49, 0x03, 0x3e, 0x10, 0xf8, 0x0d, 0x16, 0xb5,
	0x78, 0xae, 0x85, 0x7e, 0xf9, 0x9e, 0x1b, 0x11, 0x9f, 0xaf, 0x48, 0xba, 0x58, 0xb3, 0xcc, 0x87,
	0xca, 0xba, 0x50, 0xd9, 0x53, 0x17, 0x8a, 0x8f, 0xc7, 0xfd, 0xb6, 0x8b, 0xe0, 0xb6, 0x83, 0x53,
	0xb6, 0xfb, 0x71, 0x9b, 0x3a, 0xd7, 0xbf, 0x36, 0x55, 0x53, 0x9a, 0x78, 0xe6, 0x82, 0xf5, 0x38,
	0xa1, 0x00, 0x0f, 0x52, 0x72, 0x3f, 0x9d, 0xdc, 0xc1, 0xdc, 0x21, 0x25, 0x0f, 0x78, 0x0b, 0x41,
	0x61, 0xeb, 0x88, 0xc9, 0x6a, 0x9a, 0x2e, 0xd6, 0x61, 0xa6, 0xb6, 0x99, 0xeb, 0x87, 0x7b, 0x3e,
	0x79, 0x0f, 0x8b, 0xa7, 0x4a, 0xfd, 0x6c, 0x77, 0x91, 0x02, 0x29, 0x5d, 0x5f, 0x01, 0x27, 0x65,
	0xf2, 0x11, 0x42, 0x2f, 0x9e, 0x64, 0x75, 0x03, 0xf4, 0x47, 0xae, 0xcd, 0x1b, 0x5e, 0x9f, 0x00,
	0x5a, 0xf5, 0x24, 0xb3, 0x6b, 0xb8, 0x7a, 0x14, 0xc6, 0xbc, 0x96, 0x3b, 0x3d, 0xdc, 0x75, 0x39,
	0x50, 0xd6, 0x84, 0xc1, 0x5c, 0xb7, 0x84, 0xf3, 0x09, 0x79, 0x8f, 0x93, 0x08, 0xe8, 0x46, 0x8a,
	0xbc, 0xec, 0x96, 0x29, 0x40, 0x8b, 0x95, 0x3c, 0x24, 0x4b, 0x88, 0xb8, 0xff, 0x32, 0x9d, 0x1e,
	0x01, 0xed, 0x19, 0x25, 0x0f, 0xeb, 0x3f, 0x13, 0x98, 0xf9, 0xdf, 0x0f, 0x3f, 0xc0, 0xf4, 0x41,
	0x4a, 0x8c, 0x6c, 0xc6, 0xa1, 0x66, 0x46, 0x7b, 0x6c, 0x1d, 0xcf, 0x30, 0x85, 0x73, 0x5b, 0x16,
	0x5e, 0x59, 0x7e, 0xd4, 0x29, 0xbb, 0x1c, 0x08, 0x3f, 0x79, 0x07, 0x81, 0xab, 0x02, 0x97, 0x56,
	0x19, 0x77, 0xc6, 0xa2, 0x11, 0xe3, 0x87, 0xbf, 0xc2, 0xbc, 0xbb, 0x1a, 0xdf, 0x59, 0xf5, 0xbf,
	0x5a, 0xd8, 0xf5, 0x31, 0xd9, 0x3f, 0xe1, 0xce, 0xf5, 0x4f, 0x8c, 0x9b, 0xf0, 0x4f, 0x8c, 0xba,
	0x38, 0xc3, 0xcf, 0x70, 0xd1, 0xde, 0x8e, 0x68, 0xc5, 0xe3, 0x6a, 0xd8, 0xf2, 0x88, 0x73, 0x2b,
	0xdb, 0x99, 0xfb, 0x5d, 0xbf, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x03, 0x5f, 0x53, 0x16, 0xa3,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SrcctlClient is the client API for Srcctl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SrcctlClient interface {
	// Top N requests in cache
	All(ctx context.Context, in *AllRequest, opts ...grpc.CallOption) (*AllReply, error)
	TopN(ctx context.Context, in *TopNRequest, opts ...grpc.CallOption) (*TopNReply, error)
	LastN(ctx context.Context, in *LastNRequest, opts ...grpc.CallOption) (*LastNReply, error)
	Settings(ctx context.Context, in *SettingsRequest, opts ...grpc.CallOption) (*SettingsReply, error)
	Clean(ctx context.Context, in *CleanRequest, opts ...grpc.CallOption) (*CleanReply, error)
	Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshReply, error)
}

type srcctlClient struct {
	cc *grpc.ClientConn
}

func NewSrcctlClient(cc *grpc.ClientConn) SrcctlClient {
	return &srcctlClient{cc}
}

func (c *srcctlClient) All(ctx context.Context, in *AllRequest, opts ...grpc.CallOption) (*AllReply, error) {
	out := new(AllReply)
	err := c.cc.Invoke(ctx, "/pb.srcctl/All", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srcctlClient) TopN(ctx context.Context, in *TopNRequest, opts ...grpc.CallOption) (*TopNReply, error) {
	out := new(TopNReply)
	err := c.cc.Invoke(ctx, "/pb.srcctl/TopN", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srcctlClient) LastN(ctx context.Context, in *LastNRequest, opts ...grpc.CallOption) (*LastNReply, error) {
	out := new(LastNReply)
	err := c.cc.Invoke(ctx, "/pb.srcctl/LastN", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srcctlClient) Settings(ctx context.Context, in *SettingsRequest, opts ...grpc.CallOption) (*SettingsReply, error) {
	out := new(SettingsReply)
	err := c.cc.Invoke(ctx, "/pb.srcctl/Settings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srcctlClient) Clean(ctx context.Context, in *CleanRequest, opts ...grpc.CallOption) (*CleanReply, error) {
	out := new(CleanReply)
	err := c.cc.Invoke(ctx, "/pb.srcctl/Clean", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srcctlClient) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*RefreshReply, error) {
	out := new(RefreshReply)
	err := c.cc.Invoke(ctx, "/pb.srcctl/Refresh", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SrcctlServer is the server API for Srcctl service.
type SrcctlServer interface {
	// Top N requests in cache
	All(context.Context, *AllRequest) (*AllReply, error)
	TopN(context.Context, *TopNRequest) (*TopNReply, error)
	LastN(context.Context, *LastNRequest) (*LastNReply, error)
	Settings(context.Context, *SettingsRequest) (*SettingsReply, error)
	Clean(context.Context, *CleanRequest) (*CleanReply, error)
	Refresh(context.Context, *RefreshRequest) (*RefreshReply, error)
}

func RegisterSrcctlServer(s *grpc.Server, srv SrcctlServer) {
	s.RegisterService(&_Srcctl_serviceDesc, srv)
}

func _Srcctl_All_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrcctlServer).All(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.srcctl/All",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrcctlServer).All(ctx, req.(*AllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Srcctl_TopN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrcctlServer).TopN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.srcctl/TopN",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrcctlServer).TopN(ctx, req.(*TopNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Srcctl_LastN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LastNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrcctlServer).LastN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.srcctl/LastN",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrcctlServer).LastN(ctx, req.(*LastNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Srcctl_Settings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrcctlServer).Settings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.srcctl/Settings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrcctlServer).Settings(ctx, req.(*SettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Srcctl_Clean_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrcctlServer).Clean(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.srcctl/Clean",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrcctlServer).Clean(ctx, req.(*CleanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Srcctl_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrcctlServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.srcctl/Refresh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrcctlServer).Refresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Srcctl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.srcctl",
	HandlerType: (*SrcctlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "All",
			Handler:    _Srcctl_All_Handler,
		},
		{
			MethodName: "TopN",
			Handler:    _Srcctl_TopN_Handler,
		},
		{
			MethodName: "LastN",
			Handler:    _Srcctl_LastN_Handler,
		},
		{
			MethodName: "Settings",
			Handler:    _Srcctl_Settings_Handler,
		},
		{
			MethodName: "Clean",
			Handler:    _Srcctl_Clean_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _Srcctl_Refresh_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "srcctl.proto",
}
